### ISSUE TITLE
Bigger font size?

### ISSUE THREAD

**Issue by seanho00** [sermons/reveal-skel#20]
Increase base font size from theme?
The stock `black.css` theme uses `font-size: 38px`.
We could override it in `slides.css` with a more specific selector, e.g.,

``` css
.reveal section {
  font-size: 48px;
}
```

Would break existing presentations when they `git pull upstream`; may need to repaginate some slides.
