### ISSUE TITLE
Feather bg shading

### ISSUE THREAD

**Issue by seanho00** [sermons/reveal-skel#62]
Currently, shading of `section[data-background-image]` has hard edges around the content box, which is a bit distracting, particularly when the bg img is light.

Soften the edges using heavy blurring, gradient, or vignetting.

**Comment by seanho00** [comment]
Better yet, blur the *background* beneath the shading

**Comment by seanho00** [comment]
```css
.reveal .slides>section.present:before {
  background: url(''); /* snag from current slide via JS */
  background-attachment: fixed;
  background-size: (w/h)*768/1.024px 750px; /* emulate 'cover' */
  background-position: center;
  filter: blur(4px);
  content: '';
  z-index: -1;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
```

Cannot use `background: inherit` due to Reveal's backgrounds being in a separate div, controlled by JS.

+ [Usama Tahir](https://medium.com/@AmJustSam/how-to-do-css-only-frosted-glass-effect-e2666bafab91)
