### ISSUE TITLE
Use Travis gh-pages deploy

### ISSUE THREAD

**Issue by seanho00** [sermons/reveal-skel#73]
https://docs.travis-ci.com/user/deployment/pages/

Bot credentials: SSH key vs Github access token? 

Store credential in Travis account instead of in each repo?

**Comment by seanho00** [comment]
```
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
```
